### ISSUE TITLE
Simplify examples

### ISSUE THREAD

**Issue by janhohenheim** [kaosat-dev/Blenvy#123]
The current examples are functional character controllers, which is cool, but 95% of the code shown is irrelevant to the crates a newcomer is trying to learn. Personally, this made it daunting to get into an otherwise simple to use crate ecosystem. In fact, I was delighted at how little code I actually needed to setup everything once I fought my way through!

The biggest offender here is the basic component reader, which requires only a *single line of code*, namely registering the plugin. Reading the example, this fact is not obvious, as it contains not only a lot of liens but a lot of files. I recommend replacing the entire example with a single file.

In sum, I suggest removing most dynamic interactions in favor of showing a simple, boring, static scene. This might not look as impressive, but would be instantly understandable to a beginner. We could of course just add these as new examples, but I believe this would bloat the examples, as the interactive ones become dead weight to maintain.

I hope any of this doesn't come as overly harsh. My motivation is that I am *very* happy with the Blender workflow and wish to make it as accessible as possible to newcomers :)

**Comment by kaosat-dev** [comment]
Thanks for the feedback, and no it does not sound harsh at all, I agree with pretty much all your points!
In fact, I started doing that [today](https://github.com/kaosat-dev/Blender_bevy_components_workflow/tree/general_cleanup/examples/bevy_gltf_blueprints) :D

* the examples have / had  a bad signal/noise ratio, and where too numerous to be manageable , so I am extracting common code, merging some examples, removing some of them
* btw for the "basic component reader" do you mean [this](https://github.com/kaosat-dev/Blender_bevy_components_workflow/tree/main/examples/bevy_gltf_components/basic) one ?
* there is the slight added problem that the examples work both as examples of feature on the Bevy side, as well as on the Blender side, but with the trimmed down versions, it should be a lot more palatable
* I could convert one of them to being a static scene to remove the distraction ? (I need at least a few with dynamic elements to also work as testing grounds, but it should indeed not be all of them)

**Comment by janhohenheim** [comment]
> btw for the "basic component reader" do you mean [this](https://github.com/kaosat-dev/Blender_bevy_components_workflow/tree/main/examples/bevy_gltf_components/basic?rgh-link-date=2024-02-06T18%3A51%3A34Z) one ?

exactly

> I could convert one of them to being a static scene to remove the distraction ? (I need at least a few with dynamic elements to also work as testing grounds, but it should indeed not be all of them)

Having a testing ground is nice, but it handles a different concern than an example. I recommend you take that testing ground and move it to a dedicated binary. This way the testing grounds can have whatever diagnostics you need and can test multiple things at once, while the examples stay simple and readable.

**Comment by kaosat-dev** [comment]
@janhohenheim even if not perfect, I think this is resolved ?

**Comment by janhohenheim** [comment]
@kaosat-dev I think it would be best for new users if they saw the workflow in action on a simple single main.rs per example.
No physics (except for the dedicated example), no controls, no common.rs, nothing but the actual libraries in question.
If I find the time, I can write some of these and move the current ones into a "demo" folder. Feel free to assign me to this issue.
