### ISSUE TITLE
Repositioning objects doesn't re-export scene

### ISSUE THREAD

**Issue by DylanRJohnston** [kaosat-dev/Blenvy#145]
Is there any way to force the export each time instead of checking for changes? I'm encountering an issue where repositioning objects in the scene does not cause the auto export to properly save. Only deleting the `Scene.glb` properly exports the scene.

![Screenshot 2024-02-23 at 4 54 49 pm](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/443c398d-0c38-4923-a789-e7ac9256e9b9)

**Comment by DylanRJohnston** [comment]
![Screenshot 2024-02-23 at 4 55 35 pm](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/d18118dc-f8ee-447f-913a-ecf818571f35)

**Comment by DylanRJohnston** [comment]
I can confirm after forking the code that a brute force `if True:` [here](https://github.com/kaosat-dev/Blender_bevy_components_workflow/blob/e83ef32b9f8d663bcdf1cdff826d2afd0bb2427d/tools/gltf_auto_export/auto_export/auto_export.py#L114) and [here](https://github.com/kaosat-dev/Blender_bevy_components_workflow/blob/e83ef32b9f8d663bcdf1cdff826d2afd0bb2427d/tools/gltf_auto_export/auto_export/auto_export.py#L122) fixes the issue. Perhaps there could be a setting that just always exports everything? Or would you rather fix up the change detection?

**Comment by kaosat-dev** [comment]
Hi @DylanRJohnston !
Could you tell a bit more about your setup please ?
* are the objects that you are moving in a main scene, library scene etc ?
* are the objects blueprints, instances, something else ?

* I added the ability to force export (really not recommended from my experience, but it can be practical) to this pr: #143

**Comment by DylanRJohnston** [comment]
Hey @kaosat-dev, the objects in the scene are collection instances i.e. blueprints. Moving them doesn't seem to trigger the change detection code at all.

**Comment by kaosat-dev** [comment]
Hi @DylanRJohnston : 
Very weird, that always worked reliably, and is now also one of the test cases.
thanks for the info, could you please send screenshots of:
* your export settings
* your scene with the objects that you are moving, including the outliner ?

**Comment by DylanRJohnston** [comment]
Hey kaosat, apologies for not supplying more information initially, I thought the problem might be easy to reproduce for you since it was happening reliably for me, but since you already have tests covering these cases and given the other problems I've been encountering perhaps something fundamental about my setup is misconfiguration. 

![Library Outline](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/eafd9486-baa9-4fa6-8d4c-476931d5b1f2)

![Scene Outline](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/ac8a5b71-56c2-40ab-a3f7-0f59d3e423ec)


![Export Settings](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/cf1ca875-e732-4e8a-b740-c3804e4869d8)

**Comment by kaosat-dev** [comment]
Thanks for the screenshots and information !
I think I might know where the issue comes from, I need to try it out on my end too to double check : your setup seems similar to what I usually use & have in the tests **except** that your objects in your main scene are nested inside collections.
I'll get back to you once I checked things out.

**Comment by kaosat-dev** [comment]
Ok, tried it out, and still cannot reproduce the issue, change is detected correctly no matter the nesting level of an object ...

**Comment by DylanRJohnston** [comment]
How do Blender plugins handle python dependencies? Maybe I'm ending up with slightly different packages due to something in my environment?
